version: '3'

env: {}

tasks:
  bake:
    desc: "Build all docker images using docker bake"
    cmds:
      - docker buildx bake --file docker-bake.hcl

  bake:base:
    desc: "Build only the base docker image using docker bake"
    cmds:
      - docker buildx bake --file docker-bake.hcl base

  bake:base:run:
    desc: "Run the base docker image interactively"
    cmds:
      - docker run --rm -it base:latest

  bake:devops:
    desc: "Build only the devops docker image using docker bake"
    cmds:
      - docker buildx bake --file docker-bake.hcl devops

  bake:push:
    desc: "Build and push all docker images using docker bake"
    cmds:
      - docker buildx bake --file docker-bake.hcl --push
